### ISSUE TITLE
computer will not restart

### ISSUE THREAD

**Issue by sakoula** [SamLangTen/DELL-Optiplex-5080-Hackintosh#1]
Hi there and happy new year!

I am using an 5080 with Ventura and used your repository as a base. My problem is that the computer **canoot** restart and it stucks. When I shutdown it there is no problem. Is this something that you have seen? Thanks!!!!

**Comment by SamLangTen** [comment]
Hello,
I have not faced such problem. When I try to restart, it stucks for a while but restarts soon.

**Comment by sakoula** [comment]
hi, 

thanks for your reply!

i have asked the same question on another repository.

this worked for me (sonoma)

https://github.com/Stane1983/OpenCore_OptiPlex_5080/issues/5

thanks again for your time!!!!
